Diary-App.Web/Models/DiaryEntry.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Diary_App.Web.Models;

public class DiaryEntry
{
  [Key]
  public int Id { get; set; }

  [Required]
  public string Title { get; set; } = string.Empty;

  [Required]
  public string Content { get; set; } = string.Empty;

  [Required]
  public DateTime Created { get; set; } = DateTime.Now;
}

Diary-App.Web/Models/ErrorViewModel.cs
namespace Diary_App.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Diary-App.Web/Controllers/DiaryEntriesController.cs
using Diary_App.Web.Data;
using Diary_App.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Diary_App.Web.Controllers
{
  public class DiaryEntriesController : Controller
  {

    private readonly ApplicationDbContext _context;
    public DiaryEntriesController(ApplicationDbContext context)
    {
      _context = context;
    }

    // GET: DiaryEntriesController
    public ActionResult Index()
    {

      List<DiaryEntry> diaryEntries = _context.DiaryEntries.ToList();
      return View(diaryEntries);
    }

  }
}

Diary-App.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Diary_App.Web.Models;

namespace Diary_App.Web.Controllers;

public class HomeController : Controller
{
  private readonly ILogger<HomeController> _logger;

  public HomeController(ILogger<HomeController> logger)
  {
    _logger = logger;
  }

  public IActionResult Index()
  {
    return View();
  }

  public IActionResult Privacy()
  {
    return View();
  }

  public IActionResult Contact()
  {
    return View();
  }

  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  public IActionResult Error()
  {
    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
  }
}

Diary-App.Web/Views/DiaryEntries/Index.cshtml
@model List<DiaryEntry>

<div class="container">
  <div class="row pt-4">
    <div class="col-6">
      <a class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square"
          viewBox="0 0 16 16">
          <path
            d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
          <path
            d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
        </svg>
        Create new Diary Entry
      </a>
    </div>
    <div class="col-6 text-end">
      <h2>Diary Entries</h2>
    </div>
  </div>
</div>

<div class="table-responsive">

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var entry in Model)
      {
        <tr>
          <td>@entry.Title</td>
          <td>@entry.Content</td>
          <td>@entry.Created</td>
          <td>
            Edit or Delete
          </td>
        </tr>
      }
    </tbody>
  </table>
</div>

Diary-App.Web/Views/Home/Contact.cshtml
@{

}

<div>This is contact page</div>

Diary-App.Web/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

<h1>Hello Word</h1>


@section Scripts {
  <script src="~/js/site.js"></script>
}

Diary-App.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Diary App</title>
  <script type="importmap"></script>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/Diary_App.Web.styles.css" asp-append-version="true" />
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
      <div class="container-fluid">
        <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">
          Diary App
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journals"
            viewBox="0 0 16 16">
            <path
              d="M5 0h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2 2 2 0 0 1-2 2H3a2 2 0 0 1-2-2h1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1H1a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v9a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1H3a2 2 0 0 1 2-2" />
            <path
              d="M1 6v-.5a.5.5 0 0 1 1 0V6h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V9h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 2.5v.5H.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1H2v-.5a.5.5 0 0 0-1 0" />
          </svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" asp-area="" asp-controller="DiaryEntries" asp-action="Index">My Diary</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted"
    style="position: fixed; bottom: 0; width: 100%; height: 60px; line-height: 60px;">
    <div class="container">
      &copy; 2025 - Diary_App.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>